### ISSUE TITLE
test util::keypair_util::tests::keypair_generates_new_keypair_but_does_not_save_it fails on Windows

### ISSUE THREAD

**Issue by jperedadnr** [pyrsia/pyrsia#1094]
### Steps taken/Steps to reproduce

Run

```
cargo test --workspace
```

The test fails with:

```
---- util::keypair_util::tests::keypair_generates_new_keypair_but_does_not_save_it stdout ----
thread 'util::keypair_util::tests::keypair_generates_new_keypair_but_does_not_save_it' panicked at 'assertion failed: !tmp_file.as_path().exists()', src\util\keypair_util.rs:145:9
```

Adding debug info to the test:
```
println!("tmp file {:?} {}", tmp_file.as_path(), tmp_file.as_path().exists());
assert!(tmp_file.as_path().exists());
```

 On Mac:
```
tmp file "/var/folders/zx/s6qr37tn5l98xzzsxttp9lph0000gn/T/.tmpnNMunv/keypair_fails" false
```

but on Windows:

```
tmp file "C:\\Users\\$user\\AppData\\Local\\Temp\\.tmpF037IB\\keypair_fails" true
```

however I don't see it nor can't access it.

### Expected Behavior

The test doesn't fail

### Experienced Instance of the bug

rust rustc 1.64.0 (a55dd71d5 2022-09-19)  
Windows 10

**Comment by jperedadnr** [comment]
Narrowed it down to the following:

```
let tmp_dir = tempfile::tempdir().unwrap();
        let metadata = fs::metadata(&tmp_dir).unwrap();
        let mut perms = metadata.permissions();
        perms.set_readonly(true);

let tmp_file = tmp_dir.path().join("keypair_fails");
        
let res = fs::File::create(&tmp_file);
    match res {
        Ok(_) => println!("file created on a read only directory"),
        Err(e) => panic!("error!!! {:?}", e),
    }
```
    
On Mac works as expected:
```
error!!! Os { code: 13, kind: PermissionDenied, message: "Permission denied" }'
```
on Windows the file is created, but it shouldn’t:
```
file created on a read only directory
```

**Comment by tiainen** [comment]
There are currently three tests that fail when running on windows.

- `cli_commands::config::tests::test_config_file_update`: the test is relying on the `HOME` environment variable which does not exist on windows. This can be remedied by making the location of the configuration file configurable from within tests instead of relying on the way `confy` defines the default location for configuration files.
- `peer_metrics::metrics::tests::cpu_load_test`: the cpu load is always 0 on windows. We can either allow an initial zero value in the test or we can skip this test on windows.
- `util::keypair_util::tests::keypair_generates_new_keypair_but_does_not_save_it`: the test tries to simulate the fact that the keypair file can not be created when it is located inside a read-only directory. On linux and mac this will indeed fail, but on windows it's not a problem to create a file inside a read-only directory. A way to fix this is to specify a directory for storing the keypair that really can't be accessed/written into.

These three cases are not really difficult to fix (or ignore), which means that we would be able to enable testing on the windows runner in the github actions workflow.

**Comment by dasmanas** [comment]
I observed the problem of `util::keypair_util::tests::keypair_generates_new_keypair_but_does_not_save_it` in docker container. The test case was failing. Even if the permission is set to readonly for the directory, it was not in effect as the executable was running with root privilege. Therefore I hade to made the changes to run under different user and user group in the container other than root.


```
# create new user, new group and adding the user under new group
RUN groupadd -r ${USER_GRP}; \
    useradd -r -m -g ${USER_GRP} -s /bin/bash ${USER};
# change user
USER ${USER}

# copied entire pyrsia project with changed user and group ownwership
COPY --chown=${USER}:${USER_GRP} . ${HOME}/pyrsia/
```

Dockerfile reference https://github.com/pyrsia/pyrsia/blob/14e1b5ecf2c90fedb949bca54aa47759436df1c4/installers/docker/local_code_coverage/Dockerfile
