### ISSUE TITLE
Fix dependency order of  `pyrsia_client_lib` in `signed_struct`

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#110]
See https://github.com/pyrsia/pyrsia/pull/102#discussion_r769751309 for conversation

This is extremely confusing and make it very error prone.
We need to apply the suggestion from https://doc.rust-lang.org/cargo/guide/project-layout.html

https://doc.rust-lang.org/book/ch11-03-test-organization.html

https://github.com/pyrsia/pyrsia/pull/62#issuecomment-990199046

**Comment by mgrand** [comment]
@prince-chrismc Please state what circular dependency you are talking about. As far as I know there is none.

**Comment by prince-chrismc** [comment]
Client lib requires signed (I am not confident which "signed" since it was resued) 
https://github.com/pyrsia/pyrsia/blob/0ebe6fade49a4967f16d686afed7341af2a22626/pyrsia_node/pyrsia_client_lib/src/signed.rs#L80

and signed requires client lib https://github.com/pyrsia/pyrsia/blob/0ebe6fade49a4967f16d686afed7341af2a22626/pyrsia_node/pyrsia_client_lib/signed_struct/Cargo.toml#L14

But the more I look at this I think it's not really just the misplace/extra references between things that are not connected.

We need to modify these two to better match the recommend project layout from the cargo book https://doc.rust-lang.org/cargo/guide/project-layout.html

**Comment by mgrand** [comment]
@prince-chrismc You are confusing two separate things named `Signed` and `signed_struct`. There is no circular reference. Cargo complains about that.

The crate `pyrsia_client_lib` contains a trait name `Signed`. There is a procedural macro named `signed_struct` that implements the `Signed` trait for arbitrary structs. 

Rust requires procedural macros to be in a crate that contains nothing but procedural macros. For this reason, the `signed_struct` macro is in a separate crate. `signed_struct` has a dependency on `pyrsia_client_lib`. There is no dependency the other way around. 

The test for `signed_struct` cannot be in the same crate as `signed_struct` because of the restriction on having only procedural macros in the crate. Putting the test in `pyrsia_client_lib` would create a circular dependency, so I put it in a third crate named `signed_struct_test`.

The dependency relationships are that the `signed_struct_test` crate depends on the `signed_struct` crate, which depends on the `pyrsia_client_lib` crate. I don't think that the project layout example you are referencing includes a procedural macro crate.  I think that the relationships between these three crates would be clearer if the directory structure reflected the relationships.

If you want to look at other projects that do have procedural macros, I suggest you take a look at the source for the serde crate.

**Comment by prince-chrismc** [comment]
The problem is it's too convoluted. 

We do not need that many crates with nested crates at this early stage of the project. We need to avoid adding extra steps/work.

**Comment by prince-chrismc** [comment]
We should have 

```
pyrsia_node
|_ src/
|_signing
   |_ signing-marco # This seems to be a convention in rust projects (optionally at the same level as singing)
       |_ src/
       |_ tests/
   |_ src/
        lib.rs
```

https://doc.rust-lang.org/cargo/guide/tests.html?highlight=test#tests and https://doc.rust-lang.org/book/ch11-00-testing.html

explain the motivation for this.

**Comment by mgrand** [comment]
@prince-chrismc I don't know what to say that I have not already said. If you would like, we can have a live conversation about this.

**Comment by prince-chrismc** [comment]
🤔 I found my culprit...

https://github.com/pyrsia/pyrsia/blob/813134057becd880e5c68773e649bcb3521413f8/pyrsia_node/pyrsia_client_lib/signed_struct/src/lib.rs#L157

`signed_struct` point backwards to it's parent `pyrsia_client_lib`.

There's a coupled dependency on the module `signed` and `signed_struct` which **can not** be apart of the same crate.

This causes:

1. some very nasty name resolution problems because neither absolute or relative names can be used
2. The need to have two crate to use one macro (seems like a rust limitation 🤢)

related to pyrsia/pyrsia-documentation#68

**Comment by mgrand** [comment]
@prince-chrismc Yes, as I said previously, signed_struct has a dependency on pyrsia_client_lib::signed::Signed.

There is no circularity here. I do not understand why you call pyrsia_client_lib the parent of signed_struct. The only way pyrsia_client_lib looks like the parent of signed_struct is because it is in a directory under pyrsia_client_lib. It is there because you put it there. If you don't like it there then make it a top-level crate, which is the way it was originally.

**Comment by prince-chrismc** [comment]
I am beginning to appreciate the solution you put in, https://github.com/pyrsia/pyrsia/issues/110#issuecomment-995402932 did not make sense until I was playing with the structuring. This comment

> Rust requires procedural macros to be in a crate that contains nothing but procedural macros.

I think very well described the limitation you tried to work around.

Perhaps we should limit/document how to these macros for the rest of the team?

**Comment by mgrand** [comment]
Currently the best documentation for using 
`#[signed_struct]
is the test. I am fine with writing more documentation. I keep hearing from @betarelease that he hears complaints that I am writing too much documentation. If you would like more documentation, please schedule a meeting to discuss how things should be documented.

**Comment by prince-chrismc** [comment]
Documentation should not be in the code.

I would like to write a very short (10 lines) about using this type of macro so we have a baseline of understanding.
