### ISSUE TITLE
Remove hostname from pyrsia config - since it is not used anywhere

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#1106]

**Comment by erwin1** [comment]
I think it might still be useful in situations where you run have to run pyrsia in a non-default way. (e.g. binding on a specific local IP instead of localhost for some reason)

I'm moving it out of 0.2 since it would also require a lot of documentation changes.

Also, I'm going to create another issue to allow for easier configuration: when I want to switch between 2 nodes on the same localhost, I have to go through the config wizard every time, just to change the port number.

**Comment by dasmanas** [comment]
I also felt the same way while making some earlier changes. Under `pyrsia config` the current available options like `add`, `edit`, `remove`, `show` may be considered as subcommand. While host, port & disk space can be options under `add` & `edit` subcommands.

**Comment by efrisch** [comment]
Perhaps we should re-examine all of the command line options at this time, and consider making them `config` options as well. Specifically, `listen-only` and the `bootstrap_url` seem like possibilities (perhaps still overridable by command line switches). I think that would be more consistent with the other options.

**Comment by dasmanas** [comment]
Looking at the all comments

- We are not going to take out `host` as we might require it in future to bind on specific local IP instead of localhost for some reason
- with improved `pyrsia config edit` now we can configure `host`, `port` and `diskspace` individually and in combinations as well. 
```
pyrsia-config-edit 
Edits a node configuration

USAGE:
    pyrsia config {edit|-e} [OPTIONS]

OPTIONS:
    -H, --host <HOST>               Hostname
    -p, --port <PORT>               Port number
    -d, --diskspace <DISK_SPACE>    Disk space to be allocated to Pyrsia node
    -h, --help                      Print help information

```
