### ISSUE TITLE
Automatically add the first Pyrsia node as an authorized node

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#1141]
For user convenience, it is better to automatically add the first Pyrsia node as an authorized node.

**Comment by betarelease** [comment]
@fishseabowl This is not a good idea since once the network crashes any node could become first node and become authorized. This is not intended and a security issue. Let us think about this more deeply. 


Try to answer these questions:

What scenario are you trying to test? 
Where did you find that not having this hurt your userflow?

Please detail your answers here so that we can understand why we need this and how we should proceed.

In general first Pyrsia node should not become an authorized node. Authorized node is a designation that is approved by the governance board via a special key. And only that special key can make any node authorized.

**Comment by fishseabowl** [comment]
@betarelease Sorry for the confusing information. The first Pyrsia node I mentioned is the one that initializes the blockchain. It is not the first Pyrsia node to run.

I I followed the steps described in https://github.com/pyrsia/pyrsia/blob/main/docs/developers/build_from_source_docker.md to test. 

I found that  `../pyrsia authorize --peer <PEER_ID>` must be performed correctly. If you omit this step or run this step incorrectly. The demo cannot continue.

So I suggest that we can automatically add the first Pyrsia node that initializes the blockchain as an authorizing node.

**Comment by betarelease** [comment]
Basically that needs to be described well in the documentation and we can close this issue. Making a node authorized by default is still a security issue, so we can't do that. For a working demo we should specify the exact commands that need to be run in the correct order so that errors can be reduced.

Can you please elaborate on what is correct way to run this authorize command?

**Comment by betarelease** [comment]
CLosing this since we dont want to automate a node becoming authority node.
