### ISSUE TITLE
Pyrsia Test plan for 0.2

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#1178]
https://docs.google.com/spreadsheets/d/1V0XDdp5OQNktbE2s_yUtssko-R0PloYMTAR4-Ix5YfE/edit?usp=sharing

**Comment by betarelease** [comment]
Follow the test plan above and report results so that we can go to users with a story of what works and what is being optimized.

**Comment by ihcomega56** [comment]
(0.2.0 release note: https://github.com/pyrsia/pyrsia/releases/tag/v0.2.0)

On this test, following issues related to the features in the release note above were found.

issue | title | the current status
------|-----|-----
#1203|The pyrsia authorize command still creates a new block on blockchain for existing authorized nodes|Fixed in #1220 　
#1174|In windows 10 pro, after startup, Pyrsia_node stops with an anyhow error|Ignored as it is due to the connection issue
#1228|Formalize system requirement to use / build Pyrsia|Not resolved. Needs to be dealt with
