### ISSUE TITLE
Bug: artifacts must be re-provided after restart

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#1230]
Scenario:

- start node A (auhtorized)
- start node B (connected to A)
- config CLI to node B
- CLI request build
- CLI inspect-log -> works
- retrieve artifact from node B -> works
- restart node A
- start node C (connected to A)
- config CLI to node C
- inspect-log -> works
- retrieve artifact --> fails

So after restarting node A, which should provide files on the p2p network, those files are unreachable (if they weren't downloaded before - which is why the retrieval will still work from node B)

**Comment by betarelease** [comment]
is the issue that when node A restarts it does not look in the same Artifact folder? I would expect that the restart should not change state and since the artifacts were in the disk attached to node A they would be retrievable from node A. In case of authority node (which is nodeA for us) this is ok since we should not be restarting it. But if we do have to restart it should not lose those artifacts.

**Comment by erwin1** [comment]
It's not the same issue. the files are still there, but the node fails to provide them again on the p2p network.
we used to have this functionality but it was lost in the build from source refactoring. 

We'll work on a PR to fix this and we can discuss whether it's important enough to get it in, but I think it is, because there are now artifacts in the transparency log that can't be downloaded because no one provides them. (and they can't be rebuild either because they exist in the TPL already)
