### ISSUE TITLE
Update codebase to use rust 1.65

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#1288]
Since this requires some effort to ensure that it does not break things we had postponed updating rust lang. Now that we have released 0.2.0 we should be able to upgrade to this version and fix anything that breaks.

**Comment by erwin1** [comment]
as it turns out, we weren't using a fixed toolchain at all so we have been using the version github provides all along. This was recently changed from 1.64 to 1.65 https://github.com/actions/runner-images/commit/7d118628a44b22720df3c464500c43fc47cfda78

I've created #1352 to allow us to fix the toolchain version, but we need to decide which version we start with. Since we have been using a later version than we thought anyway, I'd say we can already switch to 1.65 now.

**Comment by erwin1** [comment]
@sbtaylor15 this is the issue to update the cargo.toml

**Comment by karolh2000** [comment]
@betarelease Heads up, because of https://github.com/rust-lang/rust-clippy/issues/10034 (broken Clippy) we are downgrading to 1.64. We'll skip 1.65 and will go directly to 1.67 which contains fixes for the Clippy problem.
