### ISSUE TITLE
Develop blockchain trait

### ISSUE THREAD

**Issue by chb0github** [pyrsia/pyrsia#137]
In order to define clear functionality needing proper implementation, defining a trait for the blockchain should be done

**Comment by mgrand** [comment]
@chb0github There are a few traits that I think need to be developed. The most urgent is what I was calling blockchain manager. It is the trait that will define the interface between the blockchain manager and the rest of the node. It will need to define a way to add an identity to the blockchain. It will also need to provide a way to get all of the information related to an identity.

If there is a mock blockchain implementing this the rest of the node can use the mock for now and you can develop without having to worry about the demo date.

The other traits I think are needed are for the internal use of the blockchain. Defining them will allow you to focus on the overall internal structure of the blockchain and then allow you to focus on one part at a time. Some suggestions for what these internal trait should be are:
* A committer trait that defined methods for committing blocks to the blockchain. The implementation of this will be responsible also for initiating the propagation of all new blocks to consensus nodes and the rest of the Pyrsia network.
* A consensus trait for scheduling records for consensus processing. 
* A trait to be implemented by the blockchains of non-consensus nodes to allow new blocks to be pushed to them.

**Comment by chb0github** [comment]
Some of this can already be derived from the current implementation. And I agree with your thinking mark: defining these will allow focus

I am thinking:
```rust
pub trait BlockChain {

    add_block(self, block: Block) -> Result<BlockChain,Error> // add the block to the chain
    validate(self) -> Result<BlockChain,Error> // starting with the genesis block, validate the entire chain
    add_observer(self, event: Event, observer: Observer<T>) // where T, in this case, would be a block and event would be an enum
}
```
And then:

```rust
pub trait Loadable<T> {

    load(self) -> Result<&T,Error> // loads the chain off disk and validates it
}
```
another
```rust
pub trait Storable<T> {
    store(self) -> Result<&T,Error> // saves the chain to disk
}
```

But you know, on thinking more about this, the method of propagation and where/how to store should be totally abstracted. An event based, async model is better in my opinion, as I/O is almost always the slowest part of an app. So, when a block has been added, then an event triggers and anyone who's interested can do as they wish (like save and propagate)

So, the 3 of us can freestyle these APIs. @mgrand - I get what you're saying for some of this and not others. I'll try to setup a call to discuss.

**Comment by mgrand** [comment]
@chb0github These three traits look like a start, but it is not clear to me what they are for. The `Loadable` and `Storable` traits look like they are for a layer over the local blockchain storage. I am concerned that they seem to assume that the entire blockchain will be resident in memory. While that is reasonable for now, I don't think that it is a necessary assumption. 

I would prefer to see a trait called something like `BlockchainCursor` with methods to access the current block and navigate to the next block, previous block or a random block number. Being able to access random block numbers is a feature we would use in conjunction with an index of blockchain contents.

The trait you name `BlockChain` has a name that sounds like it might be the external interface for the blockchain. However I am not sure that the methods you propose should go there. `add_block` is something that we be done only by a node that commits blocks to the blockchain, so maybe that should be part of a trait that is used by commit nodes when they have assembled records into a block. `add_block` would be responsible for for synchronously storing the block in the local store, sharing the new block with consensus nodes and any other commit nodes. `add_block` would also be responsible for asynchronously initiating the propagation of the new block to non-consensus, non-commit nodes.

I like the `add_observer` method. There should also be a `remove_observer` method.

Which trait to put a `validate` method in is unclear since we don't know when it should be called. For now the best way I can see to use `validate` is the have a daemon thread that continuously runs it and have an observer event that gets sent when the blockchain is invalid.

I hope this is helpful.

**Comment by chb0github** [comment]
`BlockChainCursor` -> `Iterator` - Yeah, most of this is meant to be an external interface for a block chain - even though it's not really necessary, defining such an interface makes clear what needs implementing.

Definitely a `remove_observer` - I wonder if rust has the observer/observable pattern built in

the `validate` method on a block chain may be called by anyone at anytime to validate the chain in its entirety. It's functionality that definitely needs to exist
