### ISSUE TITLE
Use artifact manager to store and retrieve docker manifests

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#268]
Related to #162 but unlike #162 this issue is required for the demo, otherwise the demo will store manifest data in /tmp/registry

This is a left-over from early proof-of-concepts where we stored data in /tmp/registry

Considering this demo scenario:
- docker pull image
- image is not found locally, nor on the pyrsia network
- image is pulled from docker hub, stored locally and in the Pyrsia network

At this point, the artifact blobs are stored in the artifact manager (and from there in the Pyrsia network). But the manifests are still stored in /tmp/registry.

**Comment by mgrand** [comment]
@erwin1 The manifests are now stored in the artifact manager. There is also a PackageVersion in the metadata manager that identifies the hash of the manifest. To use that manifest, we need the completion of #213, which this appears to duplicate. 

I started work on #213, but have decided to focus on the bittorrent integration because that is needed for the demo and getting the manifest from the artifact manager is a nice-to-have.  This appears to duplicate #213.

**Comment by betarelease** [comment]
Duplicate of #213
