### ISSUE TITLE
Explore how the rust libp2p implemenation deals with NAT

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#369]

**Comment by MitaliBo** [comment]
rust-libp2p recently has added support for basic hole punching, not released yet but interesting : 

https://github.com/libp2p/rust-libp2p/issues/2052
https://bafybeiev723vvaqkmcfo4yexw2vdxxgb5wwevir6cldk4iu527bi44hmoe.on.fleek.co/2022-01-20-libp2p-hole-punching/

**Comment by mxinden** [comment]
:wave: rust-libp2p maintainer here.

> not released yet but interesting

Released now.

Published blog post: https://blog.ipfs.io/2022-01-20-libp2p-hole-punching/

Tutorial: https://docs.rs/libp2p/latest/libp2p/tutorials/hole_punching/index.html

Let me know in case you need any help.

**Comment by MitaliBo** [comment]
So after the POC the conclusion is:
1) Enable the connection with "Circuit Relay v2" and  "DCUtR"
2) If the hole punching succeeds then direct connection will automatically be upgraded to leave relay server.
3) If hole punching did not succeed then we want to have the ability to still be connected using relay server. we will have to drastically increase the schedule time so that it does not dropped
4) Our central node will act as relay server

Closing this as implementation will be tracked #533
