### ISSUE TITLE
Port number for P2P connection should be predictable

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#503]
During the prep for the demo we ran into the following issue:

when a peer node starts it picks an available port for communication.

When another peer node starts it picks another available port for communication.

When we try to connect to these ports during the demo we have to configure one of them with the other peers port and restart pyrsia process/daemon.

It would make this process easy to understand and reduce confusion if we default to a predictable P2P port so that this configuration can be preloaded and preconfigured. 

There was some consensus about using 44000 port.

**Comment by sbtaylor15** [comment]
@erwin1 Does it make sense to add `-L /ip4/0.0.0.0/tcp/44000` as one of the command line parameters to the pyrsia_node service?

**Comment by erwin1** [comment]
@sbtaylor15 yes, that would make most sense to do now.

**Comment by sbtaylor15** [comment]
Added `--host 0.0.0.0` to pyrsia_node startup so it will listen on all interfaces.

**Comment by tiainen** [comment]
Just for understanding. The `--port` and `--host` arguments are used for the http listener. While the `--listen` argument is used for the p2p listener.

**Comment by erwin1** [comment]
quick note: the reason we bind http to 127.0.0.1 by default is because we wanted the http endpoints (for status and docker registry) to be exposed locally only. (definitely the docker registry API isn't supposed to be addressed by anything else than a local docker client)

so while `-H 0.0.0.0` might be a good work-around for some problems now, I'd suggest we create a new issue to investigate?

**Comment by sbtaylor15** [comment]
PR merged closing.
