### ISSUE TITLE
Extra usage of  `let _ =` clutters the code base

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#756]
There is a lot of places were a variable is declared but the result is ignored. 

There's a few places that's suppressing errors but other are adding noise to the code.

It would be ideal to clean up the usage.

--- 

If you're not going to use the result, then you don't even need `let`

_Originally posted by @chb0github in https://github.com/pyrsia/pyrsia/pull/712#discussion_r887277828_

**Comment by fishseabowl** [comment]
Compare two following programs, the second does not compile.
1:
let x = String::new();
let _ = x;
println!("{}", x);

2:
let x = String::new();
x;
println!("{}", x); // error[E0382]: borrow of moved value: x

"let _ =" still perform the right hand, just don't need the result.

**Comment by tiainen** [comment]
It is also used as a pattern for explicitly ignoring a `Result`, i.e. when calling a function that returns a result.

```
fn function_with_result() -> Result<(), String> {
    Ok(())
}

fn main() {
    // ignore the result
    let _ = function_with_result();
}
```

Omitting the ignored variable will result in the following warning:
> warning: unused `Result` that must be used

So in the case where you don't care about whether the returned `Result` is `Ok` or `Err`, you can use this pattern to ignore it. I've used it mostly in test cases where the result has no meaning for the specific test case.

The other uses in our code, is during the handling of a p2p event and we are sending the response to a Receiver via `sender.send()`. This function returns a Result, but there is really not much we can do with that result since we are in an isolated thread that is handling the event. The only thing we might consider, is to print a message in case of an error.

**Comment by dasmanas** [comment]
The code block is an example of ExpressionStatement. Refer to https://doc.rust-lang.org/reference/statements.html#expression-statements for more details. In other words it is inline expression.
```
    let x = String::new();
    x;
    println!("{}", x);
    let x = String::new();
```
throws following error.
```
error[E0382]: borrow of moved value: `x`
  --> src/main.rs:
let x = String::new();
    - move occurs because `x` has type `String`, which does not implement the `Copy` trait
x;
- value moved here
println!("{}", x);
               ^ value borrowed here after move
```

The same code can be written as an ExpressionWithBlock with a trick with the intent to produce the same output.
```
let x = String::new();
    if i==1 {
        x
    } else {
        x
    };
    println!("{}", x);
```
Here x has been passed to the expression closures instead of being an inline expression produced the similar error.
```
error[E0382]: borrow of moved value: `x`
  --> src/main.rs:
let x = String::new();
    - move occurs because `x` has type `String`, which does not implement the `Copy` trait
if i==1 {
    x
    - value moved here
} else {
    x
    - value moved here
};
println!("{}", x);
               ^ value borrowed here after move
```
let _ = EXPR; is exactly the same as an EXPR; Refer https://internals.rust-lang.org/t/pre-rfc-must-bind/12658/25 for more in depth.
